// Generated by Blocks2Cpp 0.1.0 from project "Countdown", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int main() {
    for (int i = 10; i >= 1; --i) {
        std::cout << i << '\n';
    }
    std::cout << "Liftoff!" << '\n';
    return 0;
}
