//! Diagnostics parsing against output recorded from g++ 13.3
//! (`tests/fixtures/gcc13`, regenerated by `regenerate.sh` there): the same
//! sources compiled with plain text, JSON and SARIF diagnostics must give
//! the same messages.

// Helper functions outside `#[test]`s fail the test by panicking.
#![allow(clippy::panic, clippy::expect_used)]

use std::path::{Path, PathBuf};

use b2c_toolchain::diagnostics::{
    CompilerMessage, MessageOrigin, MessageSeverity, ParsedOutput, parse_gcc_json, parse_output, parse_sarif,
    parse_text,
};
use b2c_toolchain::probe::DiagnosticsFormat;

fn fixture(name: &str) -> Vec<u8> {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "gcc13", name]
        .iter()
        .collect();
    std::fs::read(&path).unwrap_or_else(|error| panic!("{}: {error}", path.display()))
}

/// The three parses of one fixture: text, JSON (via stderr) and SARIF.
fn all_formats(name: &str) -> [(&'static str, ParsedOutput); 3] {
    let text = parse_output(
        DiagnosticsFormat::Plain,
        &fixture(&format!("{name}.plain.txt")),
        None,
    );
    let json = parse_output(DiagnosticsFormat::Json, &fixture(&format!("{name}.json")), None);
    let sarif = parse_output(
        DiagnosticsFormat::SarifFile,
        &fixture(&format!("{name}.sarif-stderr.txt")),
        Some(&fixture(&format!("{name}.sarif"))),
    );
    [("text", text), ("json", json), ("sarif", sarif)]
}

/// (severity, file, line, option) of one top-level message.
type Summary = (MessageSeverity, Option<String>, Option<u32>, Option<String>);

/// The [`Summary`] of each top-level message.
fn summary(parsed: &ParsedOutput) -> Vec<Summary> {
    parsed
        .messages
        .iter()
        .map(|m| {
            (
                m.severity,
                m.location.as_ref().map(|p| p.file.clone()),
                m.location.as_ref().map(|p| p.line),
                m.option.clone(),
            )
        })
        .collect()
}

fn location(message: &CompilerMessage) -> (&str, u32) {
    let pos = message.location.as_ref().expect("a location");
    (pos.file.as_str(), pos.line)
}

#[test]
fn errors_fixture_agrees_across_formats() {
    let [text, json, sarif] = all_formats("errors");
    let expected = vec![
        (
            MessageSeverity::Error,
            Some("src/broken.hpp".to_owned()),
            Some(4),
            Some("-fpermissive".to_owned()),
        ),
        (
            MessageSeverity::Error,
            Some("src/errors.cpp".to_owned()),
            Some(13),
            None,
        ),
        (
            MessageSeverity::Error,
            Some("src/errors.cpp".to_owned()),
            Some(14),
            None,
        ),
        (
            MessageSeverity::Error,
            Some("src/errors.cpp".to_owned()),
            Some(15),
            None,
        ),
        (
            MessageSeverity::Warning,
            Some("src/errors.cpp".to_owned()),
            Some(17),
            Some("-Wsign-compare".to_owned()),
        ),
        (
            MessageSeverity::Warning,
            Some("src/errors.cpp".to_owned()),
            Some(11),
            Some("-Wunused-variable".to_owned()),
        ),
    ];
    for (format, parsed) in [&text, &json, &sarif] {
        assert_eq!(summary(parsed), expected, "{format}");
        assert!(!parsed.truncated, "{format}");
        assert!(parsed.has_errors());
        assert_eq!(
            parsed.messages[2].message, "'undeclared_name' was not declared in this scope",
            "{format}"
        );
        assert_eq!(parsed.messages[5].message, "unused variable 'unused'", "{format}");
        assert!(
            parsed.messages[1]
                .message
                .starts_with("no match for 'operator<<'"),
            "{format}"
        );
        // The candidates are notes of the operator<< error, with one nested
        // error explaining a substitution failure (SARIF related locations
        // carry no severity, so there it is a note).
        let children = &parsed.messages[1].children;
        assert!(children.len() > 20, "{format}");
        let nested_errors = children
            .iter()
            .filter(|c| c.severity == MessageSeverity::Error)
            .count();
        assert_eq!(nested_errors, usize::from(*format != "sarif"), "{format}");
        assert!(
            children
                .iter()
                .any(|c| c.message.starts_with("template constraint failure")),
            "{format}"
        );
    }
    // Text output also says where the header was included from and which
    // function each message is in.
    let header_error = &text.1.messages[0];
    assert_eq!(header_error.included_from.len(), 1);
    assert_eq!(location_of(&header_error.included_from[0]), ("src/errors.cpp", 3));
    assert_eq!(header_error.function.as_deref(), Some("int broken_helper()"));
    assert_eq!(text.1.messages[2].function.as_deref(), Some("int main()"));
    // SARIF gives the function from its logical location.
    assert_eq!(sarif.1.messages[0].function.as_deref(), Some("broken_helper"));
    // Columns where all formats agree on the caret.
    assert_eq!(text.1.messages[2].location.as_ref().unwrap().column, Some(5));
    assert_eq!(json.1.messages[2].location.as_ref().unwrap().column, Some(5));
}

fn location_of(pos: &b2c_toolchain::diagnostics::SourcePos) -> (&str, u32) {
    (pos.file.as_str(), pos.line)
}

#[test]
fn template_fixture_keeps_instantiation_context() {
    let [text, json, sarif] = all_formats("template");
    for (format, parsed) in [&text, &json, &sarif] {
        assert_eq!(parsed.messages.len(), 1, "{format}");
        let message = &parsed.messages[0];
        assert_eq!(message.severity, MessageSeverity::Error);
        assert_eq!(location(message), ("src/template.cpp", 7), "{format}");
        assert!(
            message
                .message
                .starts_with("request for member 'size' in 'value'"),
            "{format}"
        );
    }
    let context = &text.1.messages[0].children;
    assert_eq!(context.len(), 2);
    assert!(
        context[0]
            .message
            .starts_with("In instantiation of 'T total(const std::vector<T>&) [with T = int]'")
    );
    assert_eq!(context[1].message, "required from here");
    assert_eq!(location(&context[1]), ("src/template.cpp", 14));
    assert_eq!(sarif.1.messages[0].function.as_deref(), Some("total<int>"));
}

#[test]
fn fatal_fixture_is_fatal_everywhere() {
    for (format, parsed) in all_formats("fatal") {
        assert_eq!(parsed.messages.len(), 1, "{format}: {parsed:#?}");
        let message = &parsed.messages[0];
        assert_eq!(message.severity, MessageSeverity::Fatal, "{format}");
        assert_eq!(
            message.message, "missing_header.hpp: No such file or directory",
            "{format}"
        );
        assert_eq!(location(message), ("src/fatal.cpp", 1), "{format}");
    }
}

#[test]
fn strict_fixture_warnings_with_notes() {
    for (format, parsed) in all_formats("strict") {
        assert_eq!(
            summary(&parsed),
            vec![
                (
                    MessageSeverity::Warning,
                    Some("src/strict.cpp".to_owned()),
                    Some(6),
                    Some("-Wshadow".to_owned())
                ),
                (
                    MessageSeverity::Warning,
                    Some("src/strict.cpp".to_owned()),
                    Some(10),
                    Some("-Wfloat-conversion".to_owned())
                ),
            ],
            "{format}"
        );
        assert!(!parsed.has_errors());
        let note = &parsed.messages[0].children[0];
        assert_eq!(note.message, "shadowed declaration is here", "{format}");
        assert_eq!(location(note), ("src/strict.cpp", 3), "{format}");
    }
}

#[test]
fn link_fixture_reports_undefined_references() {
    for (format, parsed) in all_formats("link") {
        let symbols: Vec<_> = parsed.messages.iter().map(|m| m.symbol.as_deref()).collect();
        assert_eq!(
            symbols,
            [Some("say(char const*)"), Some("twice(int)"), None],
            "{format}"
        );
        assert!(
            parsed.messages.iter().all(|m| m.origin == MessageOrigin::Linker),
            "{format}"
        );
        assert!(
            parsed
                .messages
                .iter()
                .all(|m| m.severity == MessageSeverity::Error),
            "{format}"
        );
        assert_eq!(parsed.messages[0].function.as_deref(), Some("main"), "{format}");
        assert_eq!(
            parsed.messages[2].message, "ld returned 1 exit status",
            "{format}"
        );
    }
}

#[test]
fn direct_parsers_accept_the_fixtures() {
    for name in ["errors", "template", "fatal", "strict", "link"] {
        let sarif = parse_sarif(&fixture(&format!("{name}.sarif"))).unwrap();
        let text = parse_text(&String::from_utf8(fixture(&format!("{name}.plain.txt"))).unwrap());
        if name != "link" {
            let json = parse_gcc_json(&fixture(&format!("{name}.json"))).unwrap();
            assert_eq!(json.messages.len(), sarif.messages.len(), "{name}");
        }
        if name != "link" {
            assert_eq!(text.messages.len(), sarif.messages.len(), "{name}");
        }
    }
}

#[test]
fn fixture_compiler_version_is_recorded() {
    let version = String::from_utf8(fixture("compiler-version.txt")).unwrap();
    assert!(version.contains("13."), "{version}");
    assert!(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/gcc13/regenerate.sh")
            .is_file()
    );
}
