//! Build script: embeds the Tauri configuration, the capability files and (on
//! Windows) the icon and manifest. It also generates a permission for each of
//! our own commands (`permissions/autogenerated/<command>.toml`), so the
//! webview can call only the commands a capability grants.

use std::env;
use std::error::Error;
use std::path::Path;

fn main() -> Result<(), Box<dyn Error>> {
    // Every command of the IPC contract needs its own `allow-…` permission in
    // `capabilities/` (docs/spec/08-security.md §8.8). The list comes from the
    // command table, the same one the TypeScript client and the isolation
    // allowlist are generated from.
    let commands = tauri_build::AppManifest::new().commands(b2c_ipc::COMMAND_NAMES);
    let mut attributes = tauri_build::Attributes::new().app_manifest(commands);
    if env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc") {
        attributes =
            attributes.windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest());
        embed_windows_manifest()?;
    }
    tauri_build::try_build(attributes)?;
    Ok(())
}

/// Embeds the application manifest (Common Controls v6) through the linker,
/// so that it is in every executable of the crate: tauri-build's resource
/// file reaches only the app binary, and a test binary without the manifest
/// does not start, because the dialog code imports `TaskDialogIndirect`,
/// which only Common Controls v6 has (`STATUS_ENTRYPOINT_NOT_FOUND`).
fn embed_windows_manifest() -> Result<(), Box<dyn Error>> {
    let manifest = Path::new(&env::var("CARGO_MANIFEST_DIR")?).join("windows-app-manifest.xml");
    let manifest = manifest.to_str().ok_or("the manifest path is not UTF-8")?;
    println!("cargo:rerun-if-changed={manifest}");
    println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
    println!("cargo:rustc-link-arg=/MANIFESTINPUT:{manifest}");
    Ok(())
}
