//! Build script: embeds the Tauri configuration, the capability files and (on
//! Windows) the icon and manifest. It also generates a permission for each of
//! our own commands (`permissions/autogenerated/<command>.toml`), so the
//! webview can call only the commands a capability grants.

use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    // Every command of the IPC contract needs its own `allow-…` permission in
    // `capabilities/` (docs/spec/08-security.md §8.8). The list comes from the
    // command table, the same one the TypeScript client and the isolation
    // allowlist are generated from.
    let commands = tauri_build::AppManifest::new().commands(b2c_ipc::COMMAND_NAMES);
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(commands))?;
    Ok(())
}
