//! Build script: embeds the Tauri configuration, the capability files and (on
//! Windows) the icon and the application manifest. It also generates a
//! permission for each of our own commands
//! (`permissions/autogenerated/<command>.toml`), so the webview can call only
//! the commands a capability grants.

use std::env;
use std::error::Error;
use std::path::{Path, PathBuf};

/// The application manifest, `windows-app-manifest.xml` next to this file:
/// Common Controls v6 (the native dialogs need it) and `longPathAware`
/// (`docs/spec/08-security.md` §8.6). `tools/check-windows-manifest.ps1`
/// checks both in the built executable.
const MANIFEST: &str = "windows-app-manifest.xml";

fn main() -> Result<(), Box<dyn Error>> {
    // Every command of the IPC contract needs its own `allow-…` permission in
    // `capabilities/` (docs/spec/08-security.md §8.8). The list comes from the
    // command table, the same one the TypeScript client and the isolation
    // allowlist are generated from.
    let commands = tauri_build::AppManifest::new().commands(b2c_ipc::COMMAND_NAMES);
    let mut attributes = tauri_build::Attributes::new().app_manifest(commands);
    let windows = env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");
    if windows {
        let manifest = manifest_path()?;
        println!("cargo:rerun-if-changed={}", manifest.display());
        let windows_attributes = if env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc") {
            embed_windows_manifest(&manifest)?;
            tauri_build::WindowsAttributes::new_without_app_manifest()
        } else {
            // MinGW: tauri-build's resource file, which reaches the app's
            // executable only (test binaries there have no manifest, as
            // before; CI tests on Windows use MSVC).
            tauri_build::WindowsAttributes::new().app_manifest(std::fs::read_to_string(&manifest)?)
        };
        attributes = attributes.windows_attributes(windows_attributes);
    }
    tauri_build::try_build(attributes)?;
    Ok(())
}

/// The absolute path of [`MANIFEST`].
fn manifest_path() -> Result<PathBuf, Box<dyn Error>> {
    Ok(Path::new(&env::var("CARGO_MANIFEST_DIR")?).join(MANIFEST))
}

/// MSVC: embeds the application manifest through the linker, so that it is
/// in every executable of the crate. tauri-build's own resource file
/// (`WindowsAttributes::app_manifest`) reaches only the app binary, and a
/// test binary without the manifest does not start, because the dialog code
/// imports `TaskDialogIndirect`, which only Common Controls v6 has
/// (`STATUS_ENTRYPOINT_NOT_FOUND`). So tauri-build's manifest is turned off
/// (`new_without_app_manifest`) and the linker merges this one into the
/// manifest it generates (`/MANIFEST:EMBED`, `/MANIFESTINPUT`).
fn embed_windows_manifest(manifest: &Path) -> Result<(), Box<dyn Error>> {
    let manifest = manifest.to_str().ok_or("the manifest path is not UTF-8")?;
    println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
    println!("cargo:rustc-link-arg=/MANIFESTINPUT:{manifest}");
    Ok(())
}
