// Generated by Blocks2Cpp 0.1.0 from project "Hello World", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int main() {
    std::cout << "Hello, world!" << '\n';
    return 0;
}
