// Generated by Blocks2Cpp 0.1.0 from project "Factorial", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int factorial(int n);

// n! = n × (n − 1)!
int factorial(int n) {
    if (n <= 1) {
        return 1;
    }
    return n * factorial(n - 1);
}

int main() {
    for (int i = 1; i <= 10; ++i) {
        std::cout << i << "! = " << factorial(i) << '\n';
    }
    return 0;
}
