// Generated by Blocks2Cpp 0.1.0 from project "Greeting", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <cstdlib>
#include <iostream>
#include <string>

// ---- Blocks2Cpp support helpers (only those used) ------------------------
namespace b2c {

/// Prints `prompt` and reads a line of text, skipping empty lines and leading
/// spaces. At the end of the input (for example when the input comes from a
/// file), prints "Input ended" to the error stream and exits with code 1.
inline std::string ask_line(const std::string& prompt = "") {
    std::cout << prompt;
    std::string line;
    if (!std::getline(std::cin >> std::ws, line)) {
        std::cerr << "Input ended" << '\n';
        std::exit(1);
    }
    if (!line.empty() && line.back() == '\r') {
        line.pop_back();
    }
    return line;
}

}  // namespace b2c
// ---- End of Blocks2Cpp support helpers -----------------------------------

int main() {
    std::string name{};
    name = b2c::ask_line("What is your name? ");
    std::cout << std::string("Hello, ") + name + "!" << '\n';
    return 0;
}
