// Writes the block reference, docs/reference/blocks/ (docs/spec/09-quality-and-delivery.md
// §9.4): README.md with the list of categories and how to read the tables, and one page per
// toolbox category with a table of its blocks and the category's toolbox entries.
//
// The output must pass markdownlint (.markdownlint-cli2.jsonc): catalog text is escaped, so it
// can never become Markdown structure or HTML.

import type {
  BlockDefJson,
  ExtraDefJson,
  FieldDefJson,
  InputDefJson,
  PresetJson,
  RepeatJson,
  StatementDefJson,
  TokenJson,
  ToolboxCategoryJson,
  ToolboxEntryJson,
  TypeClass,
} from './catalog-types.ts';
import type { Model } from './normalize.ts';

/** Where the reference goes, relative to the repository root. */
export const REFERENCE_DIR = 'docs/reference/blocks';

const GENERATED_NOTE =
  '<!-- @generated by @blocks2cpp/catalog-gen from packages/catalog-gen/catalog.json. Do not edit: change catalog/ and regenerate (see packages/catalog-gen/README.md). -->';

const TABLE_HEADER = [
  '| Block | Friendly label | C++ form | Help | Fields | Inputs |',
  '| --- | --- | --- | --- | --- | --- |',
];

/** The reference's files, by file name, in a fixed order: README.md first. */
export function blockReference(model: Model): Map<string, string> {
  const files = new Map<string, string>();
  const pages = model.toolbox.map((category) => ({
    category,
    blocks: blocksOf(category, model.blocks),
  }));
  const listed = pages.reduce((sum, page) => sum + page.blocks.length, 0);
  if (listed !== model.blocks.length) {
    throw new Error(
      `the toolbox categories cover ${String(listed)} of ${String(model.blocks.length)} blocks`,
    );
  }
  files.set('README.md', readme(model, pages));
  for (const page of pages) {
    files.set(`${page.category.id}.md`, categoryPage(page.category, page.blocks));
  }
  return files;
}

/** A category's blocks: in toolbox order, then the ones only the editor adds, by ID. */
function blocksOf(category: ToolboxCategoryJson, blocks: readonly BlockDefJson[]): BlockDefJson[] {
  const own = blocks.filter((block) => block.category === category.id);
  const order = [...new Set(category.entries.map((entry) => entry.block))];
  const rank = (block: BlockDefJson): number => {
    const index = order.indexOf(block.id);
    return index < 0 ? order.length : index;
  };
  return own.sort((a, b) => rank(a) - rank(b) || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

function readme(
  model: Model,
  pages: readonly { category: ToolboxCategoryJson; blocks: readonly BlockDefJson[] }[],
): string {
  const rows = pages.map(
    ({ category, blocks }) =>
      `| [${text(category.name)}](${category.id}.md) | ${text(category.icon)} | ${String(blocks.length)} |`,
  );
  return lines([
    '# Block reference',
    '',
    GENERATED_NOTE,
    '',
    'Every block of the Blocks2Cpp core catalog, by toolbox category. The editor and the',
    'compiler both use the catalog, and this reference is generated from it, so the three',
    'always agree ([spec §3.11.1](../../spec/03-block-language.md#3111-catalog-format)).',
    '',
    `Catalog version: ${text(model.catalogVersion)}.`,
    '',
    '| Category | Icon | Blocks |',
    '| --- | --- | --- |',
    ...rows,
    '',
    '## How to read the tables',
    '',
    '* **Block**: the block ID and the block shape',
    '  ([spec §3.3](../../spec/03-block-language.md#33-block-shapes)). A block that gives a',
    '  value also says the type of the value.',
    '* **Friendly label** and **C++ form**: the text of the block in the two display modes',
    '  ([spec §3.5.2](../../spec/03-block-language.md#352-friendly-and-c-display-modes)).',
    '  `%NAME` marks where the field or input `NAME` goes, and `…` marks where a repeated part',
    '  continues: ⊕ on the block adds one, ⊖ removes one.',
    '* **Help**: the tooltip.',
    '* **Fields**: the values set on the block itself, with their choices and defaults.',
    '* **Inputs**: the slots for values (with the kind of value each one takes, and the value',
    '  shown while it is empty), the slots for blocks, and the settings that add or remove',
    '  slots.',
    '',
    'Each page ends with the entries of its toolbox category, in order, including the ones that',
    'start with other values than the defaults.',
  ]);
}

function categoryPage(category: ToolboxCategoryJson, blocks: readonly BlockDefJson[]): string {
  const entries = category.entries.map(
    (entry, index) => `${String(index + 1)}. ${entryText(entry)}`,
  );
  const named = new Set(category.entries.map((entry) => entry.block));
  const added = blocks.filter((block) => !named.has(block.id)).map((block) => code(block.id));
  const toolbox: string[] = [...entries];
  if (category.dynamic !== null) {
    if (toolbox.length > 0) {
      toolbox.push('');
    }
    toolbox.push(
      category.dynamic === 'variables'
        ? `The editor also adds a getter for every variable in scope at the selected block, and the blocks that change a variable, preset to it: ${list(added, 'and')}.`
        : `*My Blocks*: the editor also adds a call block for every function of the project: ${list(added, 'and')}.`,
    );
  }
  return lines([
    `# ${text(category.name)}`,
    '',
    GENERATED_NOTE,
    '',
    `Toolbox icon: ${text(category.icon)}. Back to [all categories](README.md).`,
    '',
    '## Blocks',
    '',
    ...TABLE_HEADER,
    ...blocks.map(blockRow),
    '',
    '## In the toolbox',
    '',
    ...toolbox,
  ]);
}

function blockRow(block: BlockDefJson): string {
  const cells = [
    blockCell(block),
    code(block.label.friendly),
    code(block.label.cpp),
    text(block.help),
    sentences(block.fields.map((field) => fieldText(field, block))),
    sentences([
      ...block.inputs.map(inputText),
      ...block.statements.map(statementText),
      ...block.extra.map(extraText),
    ]),
  ];
  return `| ${cells.join(' | ')} |`;
}

function blockCell(block: BlockDefJson): string {
  const gives = block.output === null ? '' : `, gives ${outputText(block)}`;
  return `${code(block.id)} (${block.shape}${gives})`;
}

function outputText(block: BlockDefJson): string {
  const output = block.output ?? 'any';
  switch (output) {
    case 'any':
      return 'a value of any type';
    case 'number':
      return `${code('int')} or ${code('double')}`;
    case 'string':
      return code('std::string');
    case 'bool':
    case 'int':
    case 'double':
    case 'char':
      return code(output);
    case 'symbol': {
      const reference = block.fields.find((field) => field.kind === 'symbol_ref');
      return reference === undefined
        ? 'the type of the symbol it uses'
        : `the type of ${code(reference.name)}`;
    }
    default:
      return `the type chosen in ${code(output.slice('field:'.length))}`;
  }
}

function fieldText(field: FieldDefJson, block: BlockDefJson): string {
  const name = code(field.name);
  switch (field.kind) {
    case 'dropdown': {
      // The label as shown, with the stored value when it differs.
      const options = field.options.map(([label, value]) =>
        label === value ? code(value) : `${text(label)} (${code(value)})`,
      );
      return `${name}: one of ${list(options)}${defaultText(field)}.`;
    }
    case 'checkbox':
      return `${name}: on or off${defaultText(field)}.`;
    case 'text':
      return `${name}: text${defaultText(field)}.`;
    case 'number':
      return `${name}: a number${defaultText(field)}.`;
    case 'type':
      return `${name}: a type, ${list(field.types.map(code))}${defaultText(field)}.`;
    case 'symbol_decl':
      return `${name}: the name of the new ${block.category === 'functions' ? 'function' : 'variable'}.`;
    case 'symbol_ref':
      return `${name}: the ${block.category === 'functions' ? 'function' : 'variable'} it uses.`;
  }
}

function defaultText(field: FieldDefJson): string {
  if (field.default === null) {
    return ', required';
  }
  if (typeof field.default === 'boolean') {
    return `, default ${onOff(field.default)}`;
  }
  return field.default === '' ? ', default empty' : `, default ${code(field.default)}`;
}

const CHECKS: Readonly<Record<TypeClass, string>> = {
  any: 'any value',
  number: 'a number',
  integer: 'a whole number',
  bool: 'a condition',
  text: 'text',
};

function inputText(input: InputDefJson): string {
  const value =
    input.default.length > 0
      ? `default ${code(input.default.map(tokenText).join(' '))}`
      : input.optional
        ? 'optional'
        : 'required';
  return `${partNames(input.name, input.repeat)}: ${CHECKS[input.check]}${repeatText(input.repeat)}; ${value}.`;
}

function statementText(statement: StatementDefJson): string {
  const when = statement.when === null ? '' : `, while ${code(statement.when)} is on`;
  return `${partNames(statement.name, statement.repeat)}: blocks${repeatText(statement.repeat)}${when}.`;
}

function extraText(extra: ExtraDefJson): string {
  const name = `Setting ${code(extra.name)}`;
  switch (extra.kind) {
    case 'count': {
      const range = `${String(extra.min ?? 0)} to ${String(extra.max ?? 0)}`;
      const value = typeof extra.default === 'number' ? `, default ${String(extra.default)}` : '';
      return `${name}: ${range}${value}.`;
    }
    case 'flag': {
      const value = typeof extra.default === 'boolean' ? `, default ${onOff(extra.default)}` : '';
      return `${name}: on or off${value}.`;
    }
    case 'params':
      return `${name}: up to ${String(extra.max ?? 0)} parameters, each ${list(extra.types.map(code))}.`;
  }
}

function partNames(name: string, repeat: RepeatJson | null): string {
  return repeat === null ? code(name) : `${code(`${name}0`)}, ${code(`${name}1`)}, …`;
}

function repeatText(repeat: RepeatJson | null): string {
  if (repeat === null) {
    return '';
  }
  return repeat.plus === 0
    ? `, one for each of ${code(repeat.count)}`
    : `, ${String(repeat.plus)} more than ${code(repeat.count)}`;
}

function entryText(entry: ToolboxEntryJson): string {
  const label = entry.label === null ? '' : `, labelled “${text(entry.label)}”`;
  const preset = entry.preset === null ? '' : `, with ${presetText(entry.preset)}`;
  return `${code(entry.block)}${label}${preset}`;
}

function presetText(preset: PresetJson): string {
  const parts: string[] = [];
  for (const [name, value] of Object.entries(preset.fields ?? {})) {
    parts.push(`${code(name)} set to ${valueText(value)}`);
  }
  for (const [name, value] of Object.entries(preset.extra ?? {})) {
    parts.push(
      typeof value === 'boolean'
        ? `${code(name)} ${onOff(value)}`
        : `${code(name)} set to ${valueText(value)}`,
    );
  }
  for (const [name, tokens] of Object.entries(preset.inputs ?? {})) {
    parts.push(`the input ${code(name)} set to ${code(tokens.map(tokenText).join(' '))}`);
  }
  return list(parts, 'and');
}

function valueText(value: unknown): string {
  if (typeof value === 'boolean') {
    return onOff(value);
  }
  if (typeof value === 'string' || typeof value === 'number') {
    return code(String(value));
  }
  return code(JSON.stringify(value));
}

/** A token as it reads in the editor: `0`, `"text"`, `'a'`, `true`, `+`. */
export function tokenText(token: TokenJson): string {
  if ('num' in token) return token.num;
  if ('str' in token) return JSON.stringify(token.str);
  if ('chr' in token) return `'${token.chr.replace(/[\\']/gu, (c) => `\\${c}`)}'`;
  if ('ref' in token) return token.ref;
  if ('op' in token) return token.op;
  if ('kw' in token) return token.kw;
  return token.text;
}

function onOff(value: boolean): string {
  return value ? 'on' : 'off';
}

/** `a`, `a or b`, `a, b or c` (or with `and`). */
function list(items: readonly string[], conjunction: 'or' | 'and' = 'or'): string {
  if (items.length <= 1) {
    return items[0] ?? 'nothing';
  }
  return `${items.slice(0, -1).join(', ')} ${conjunction} ${items[items.length - 1] ?? ''}`;
}

/** Sentences joined by spaces, or a dash for none. */
function sentences(all: readonly string[]): string {
  return all.length === 0 ? '—' : all.join(' ');
}

/**
 * Plain catalog text in Markdown: every character that could start Markdown structure or HTML
 * is escaped, and line breaks become spaces (a table row is one line).
 */
export function text(value: string): string {
  return value.replace(/\s+/gu, ' ').replace(/[\\`*_[\]<>|~&]/gu, (c) => `\\${c}`);
}

/**
 * Catalog text as inline code. The fence is longer than any run of backticks inside, and `|` is
 * written `\|` because the code sits in a table cell. Empty text has no code form.
 *
 * Code spans have no escapes, and GFM renderers disagree about a backslash directly before a
 * `|` in a table cell (GitHub takes every `\|` as an escaped pipe; marked, which builds the
 * site, counts the backslashes before it). No code span renders such text exactly in both, so
 * it is written as escaped plain text instead, which both read the same way.
 */
export function code(value: string): string {
  const flat = value.replace(/\s+/gu, ' ').trim();
  if (flat === '') {
    return 'nothing';
  }
  if (flat.includes('\\|')) {
    return text(flat);
  }
  const longest = Math.max(0, ...[...flat.matchAll(/`+/gu)].map((run) => run[0].length));
  const fence = '`'.repeat(longest + 1);
  const pad = flat.startsWith('`') || flat.endsWith('`') ? ' ' : '';
  // Every `|` here follows a character other than a backslash (checked above).
  const cell = Array.from(flat, (c) => (c === '|' ? '\\|' : c)).join('');
  return `${fence}${pad}${cell}${pad}${fence}`;
}

function lines(all: readonly string[]): string {
  return `${all.join('\n')}\n`;
}
