// Writes packages/blockly-ext/src/generated/catalog.ts: the types of catalog-types.ts, copied in
// so the module is self-contained, and the block definitions and toolbox as typed constants.

import type { Model } from './normalize.ts';

/** Where the generated module goes, relative to the repository root. */
export const CATALOG_TS_PATH = 'packages/blockly-ext/src/generated/catalog.ts';

const HEADER = `// @generated by @blocks2cpp/catalog-gen from packages/catalog-gen/catalog.json, which
// crates/b2c-catalog/tests/export.rs exports from the validated catalog in catalog/.
// Do not edit: change catalog/ and regenerate (see packages/catalog-gen/README.md).
`;

/**
 * The module's source before formatting. The data is written as JSON, which is valid TypeScript
 * expression syntax, so no catalog text can become code.
 *
 * @param typesSource the text of catalog-types.ts; its leading comment block is replaced by the
 *   generated-file header.
 */
export function catalogTs(model: Model, typesSource: string): string {
  const types = stripLeadingComments(typesSource);
  return [
    HEADER,
    types.trimEnd(),
    '',
    '/** The catalog version (semver of catalog/). */',
    `export const CATALOG_VERSION = ${JSON.stringify(model.catalogVersion)};`,
    '',
    '/** Every block definition of the catalog, sorted by ID. */',
    `export const BLOCK_DEFS: readonly BlockDefJson[] = ${JSON.stringify(model.blocks)};`,
    '',
    '/** The toolbox categories, in toolbox order. */',
    `export const TOOLBOX: readonly ToolboxCategoryJson[] = ${JSON.stringify(model.toolbox)};`,
    '',
  ].join('\n');
}

/** Drops the `//` comment lines (and blank lines) at the top of a source file. */
function stripLeadingComments(source: string): string {
  const lines = source.split('\n');
  const first = lines.findIndex((line) => line.trim() !== '' && !line.startsWith('//'));
  return first < 0 ? '' : lines.slice(first).join('\n');
}
