//! Emission: prints the C++ AST and lays out whole files (spec §6.7, §6.8.3).
//!
//! Layout: attached braces, braces on every control-flow body, one statement
//! per line, comments on the lines above what they describe, sections
//! separated by exactly one empty line. A stream statement (`std::cout << …`)
//! longer than [`LINE_WIDTH`] continues on the next lines, each continuation
//! starting with `<<` under the first one. Order within a source file: header
//! comment, includes, support helpers, forward declarations, function
//! definitions (sorted by name), `main`.

use std::collections::BTreeSet;

use b2c_ir::source_map::MappedRange;
use b2c_ir::text::Comment;

use crate::cast::{
    BinOp, CBlock, CExpr, CExprKind, CFunction, CParam, CStmt, CStmtKind, Callee, ForStep, Init, ParamStyle,
};
use crate::helpers::{self, Helper};
use crate::lower::LoweredModule;
use crate::{CodegenOptions, HelperPlacement};

/// Preferred maximum line length (spec §6.8.3).
const LINE_WIDTH: usize = 100;

/// Path of the shared support header.
pub(crate) const SUPPORT_HEADER: &str = "b2c_support.hpp";

/// The second line of the file header.
const DO_NOT_EDIT: &str = "// Edit the blocks, not this file – changes here are overwritten.";

/// Maximum number of characters of a name shown in the header comment.
const MAX_HEADER_NAME_CHARS: usize = 200;

/// Shortens user text for the header comment.
fn shorten(text: &str) -> String {
    match text.char_indices().nth(MAX_HEADER_NAME_CHARS) {
        Some((cut, _)) => format!("{}…", &text[..cut]),
        None => text.to_owned(),
    }
}

/// What a generated file contains, for its header comment.
enum Subject<'a> {
    /// A module's source file.
    Module(&'a str),
    /// The support header.
    Support,
}

/// Writes the header comment. The project and module names are user text,
/// so the whole line goes through the comment encoder.
fn file_header(p: &mut crate::printer::Printer, options: &CodegenOptions, subject: &Subject<'_>) {
    let version = shorten(&options.app_version);
    let generator = if version.is_empty() {
        String::from("Blocks2Cpp")
    } else {
        format!("Blocks2Cpp {version}")
    };
    let project = shorten(&options.project_name);
    let text = match subject {
        Subject::Module(module) => {
            format!(
                "Generated by {generator} from project \"{project}\", module \"{}\".",
                shorten(module)
            )
        }
        Subject::Support => format!("Generated by {generator} from project \"{project}\": support helpers."),
    };
    if let Ok(comment) = Comment::new(&text) {
        p.comment(&comment);
    } else {
        p.fixed("// Generated by Blocks2Cpp.");
        p.newline();
    }
    if options.do_not_edit_banner {
        p.fixed(DO_NOT_EDIT);
        p.newline();
    }
}

/// Writes `#include <…>` lines.
fn includes(p: &mut crate::printer::Printer, headers: &BTreeSet<&'static str>) {
    if headers.is_empty() {
        return;
    }
    p.section();
    for header in headers {
        p.fixed("#include ");
        p.fixed(header);
        p.newline();
    }
}

/// Writes the bodies of the given helpers inside `namespace b2c`.
fn helper_namespace(p: &mut crate::printer::Printer, used: &BTreeSet<Helper>) {
    p.fixed("namespace b2c {");
    p.newline();
    for helper in used {
        p.section();
        p.fixed_lines(helper.source());
    }
    p.section();
    p.fixed("}  // namespace b2c");
    p.newline();
}

/// Prints a module's source file. Returns the text and its source-map ranges.
pub(crate) fn source_file(
    module: &LoweredModule,
    module_name: &str,
    options: &CodegenOptions,
) -> (String, Vec<MappedRange>) {
    let mut p = crate::printer::Printer::new(options.indent_width);
    file_header(&mut p, options, &Subject::Module(module_name));
    let helpers_used = &module.usage.helpers;
    let inline = options.helper_placement == HelperPlacement::Inline;
    let mut headers = module.usage.includes.clone();
    if inline {
        headers.extend(helpers_used.iter().flat_map(|h| h.headers()));
    }
    includes(&mut p, &headers);
    if !helpers_used.is_empty() {
        p.section();
        if inline {
            p.fixed(helpers::SECTION_START);
            p.newline();
            helper_namespace(&mut p, helpers_used);
            p.fixed(helpers::SECTION_END);
            p.newline();
        } else {
            p.fixed("#include \"b2c_support.hpp\"");
            p.newline();
        }
    }
    let mut emitter = Emitter { p };
    if !module.functions.is_empty() {
        emitter.p.section();
        for function in &module.functions {
            emitter.declaration(function);
        }
    }
    for function in module.functions.iter().chain(&module.mains) {
        emitter.p.section();
        emitter.definition(function);
    }
    emitter.p.finish()
}

/// Prints the shared support header with the given helpers.
pub(crate) fn support_header(used: &BTreeSet<Helper>, options: &CodegenOptions) -> String {
    let mut p = crate::printer::Printer::new(options.indent_width);
    file_header(&mut p, options, &Subject::Support);
    p.section();
    p.fixed("#pragma once");
    p.newline();
    let headers = used.iter().flat_map(|h| h.headers()).copied().collect();
    includes(&mut p, &headers);
    p.section();
    helper_namespace(&mut p, used);
    p.finish().0
}

/// Prints CAST nodes.
struct Emitter {
    p: crate::printer::Printer,
}

impl Emitter {
    /// `ret name(params)`.
    fn signature(&mut self, function: &CFunction) {
        self.p.fixed(function.ret.spelling());
        self.p.fixed(" ");
        self.p.ident(&function.name);
        self.p.fixed("(");
        for (index, param) in function.params.iter().enumerate() {
            if index > 0 {
                self.p.fixed(", ");
            }
            self.param(param);
        }
        self.p.fixed(")");
    }

    /// `int x`, `int& x` or `const std::string& x`.
    fn param(&mut self, param: &CParam) {
        let start = self.p.position();
        if param.style == ParamStyle::ConstRef {
            self.p.fixed("const ");
        }
        self.p.fixed(param.ty.spelling());
        if param.style != ParamStyle::Value {
            self.p.fixed("&");
        }
        self.p.fixed(" ");
        self.p.ident(&param.name);
        self.p.map(start, &param.origin);
    }

    /// A forward declaration: `ret name(params);`.
    fn declaration(&mut self, function: &CFunction) {
        let start = self.p.position();
        self.signature(function);
        self.p.fixed(";");
        self.p.map(start, &function.origin);
        self.p.newline();
    }

    /// A function definition with its comment.
    fn definition(&mut self, function: &CFunction) {
        let start = self.p.position();
        if let Some(comment) = &function.comment {
            self.p.comment(comment);
        }
        self.signature(function);
        self.p.fixed(" ");
        self.block(&function.body);
        self.p.map(start, &function.origin);
        self.p.newline();
    }

    /// `{`, the statements one level deeper, `}`.
    fn block(&mut self, block: &CBlock) {
        self.p.fixed("{");
        self.p.newline();
        self.p.indent();
        for stmt in &block.stmts {
            self.stmt(stmt);
            self.p.newline();
        }
        self.p.dedent();
        self.p.fixed("}");
    }

    /// A statement with its comment, without the final line break.
    fn stmt(&mut self, stmt: &CStmt) {
        let start = self.p.position();
        if let Some(comment) = &stmt.comment {
            self.p.comment(comment);
        }
        self.stmt_kind(&stmt.kind);
        if let Some(origin) = &stmt.origin {
            self.p.map(start, origin);
        }
    }

    /// The statement itself.
    fn stmt_kind(&mut self, kind: &CStmtKind) {
        match kind {
            CStmtKind::Decl {
                is_const,
                ty,
                name,
                init,
            } => {
                if *is_const {
                    self.p.fixed("const ");
                }
                self.p.fixed(ty.spelling());
                self.p.fixed(" ");
                self.p.ident(name);
                match init {
                    Init::Value(value) => {
                        self.p.fixed(" = ");
                        self.expr(value);
                    }
                    Init::Braces => self.p.fixed("{}"),
                }
                self.p.fixed(";");
            }
            CStmtKind::Expr(expr) => {
                self.expr_statement(expr);
                self.p.fixed(";");
            }
            CStmtKind::Assign { target, op, value } => {
                self.p.ident(target);
                self.p.fixed(" ");
                self.p.fixed(op.token());
                self.p.fixed(" ");
                self.expr(value);
                self.p.fixed(";");
            }
            CStmtKind::Inc { target, op } => {
                self.p.fixed(op.token());
                self.p.ident(target);
                self.p.fixed(";");
            }
            CStmtKind::If { branches, else_body } => self.if_stmt(branches, else_body.as_ref()),
            CStmtKind::While { cond, body } => {
                self.p.fixed("while (");
                self.expr(cond);
                self.p.fixed(") ");
                self.block(body);
            }
            CStmtKind::For {
                ty,
                decls,
                cond,
                step,
                body,
            } => {
                self.p.fixed("for (");
                self.p.fixed(ty.spelling());
                for (index, decl) in decls.iter().enumerate() {
                    self.p.fixed(if index == 0 { " " } else { ", " });
                    self.p.ident(&decl.name);
                    self.p.fixed(" = ");
                    self.expr(&decl.value);
                }
                self.p.fixed("; ");
                self.expr(cond);
                self.p.fixed("; ");
                self.for_step(step);
                self.p.fixed(") ");
                self.block(body);
            }
            CStmtKind::Break => self.p.fixed("break;"),
            CStmtKind::Continue => self.p.fixed("continue;"),
            CStmtKind::Return(value) => {
                self.p.fixed("return");
                if let Some(value) = value {
                    self.p.fixed(" ");
                    self.expr(value);
                }
                self.p.fixed(";");
            }
            CStmtKind::Seq(stmts) => {
                for (index, stmt) in stmts.iter().enumerate() {
                    if index > 0 {
                        self.p.newline();
                    }
                    self.stmt(stmt);
                }
            }
            CStmtKind::Block(block) => self.block(block),
            CStmtKind::Error => self.p.fixed("/* error */;"),
        }
    }

    /// An expression statement (without the `;`). Long stream chains wrap:
    ///
    /// ```text
    /// std::cout << a << " " << b << …
    ///           << c << '\n';
    /// ```
    fn expr_statement(&mut self, expr: &CExpr) {
        let mut operands = Vec::new();
        stream_operands(expr, &mut operands);
        let start = self.p.position().column as usize;
        let Some((head, rest)) = operands
            .split_first()
            .filter(|_| start + flat_width(expr) > LINE_WIDTH)
        else {
            self.expr(expr);
            return;
        };
        self.expr(head);
        let align = self.p.position().column.saturating_add(1);
        for (index, operand) in rest.iter().enumerate() {
            // ` << operand`, plus the `;` after the last operand.
            let width = 4 + flat_width(operand) + usize::from(index + 1 == rest.len());
            let used = self.p.position().column as usize - 1;
            if index > 0 && used + width > LINE_WIDTH {
                self.p.newline_aligned(align);
                self.p.fixed("<< ");
            } else {
                self.p.fixed(" << ");
            }
            self.expr(operand);
        }
    }

    /// `if (…) { … } else if (…) { … } else { … }`.
    fn if_stmt(&mut self, branches: &[(CExpr, CBlock)], else_body: Option<&CBlock>) {
        for (index, (cond, body)) in branches.iter().enumerate() {
            self.p.fixed(if index == 0 { "if (" } else { " else if (" });
            self.expr(cond);
            self.p.fixed(") ");
            self.block(body);
        }
        if let Some(body) = else_body {
            self.p.fixed(" else ");
            self.block(body);
        }
    }

    /// The third clause of a `for` loop.
    fn for_step(&mut self, step: &ForStep) {
        match step {
            ForStep::Inc(op, name) => {
                self.p.fixed(op.token());
                self.p.ident(name);
            }
            ForStep::Assign(op, name, amount) => {
                self.p.ident(name);
                self.p.fixed(" ");
                self.p.fixed(op.token());
                self.p.fixed(" ");
                self.expr(amount);
            }
        }
    }

    /// An expression, recording a source-map range for each of its origins.
    fn expr(&mut self, expr: &CExpr) {
        let start = self.p.position();
        match &expr.kind {
            CExprKind::Num(lit) => self.p.num(lit),
            CExprKind::Str(lit) => self.p.str_lit(lit),
            CExprKind::Char(lit) => self.p.char_lit(*lit),
            CExprKind::Fixed(text) => self.p.fixed(text),
            CExprKind::Name(name) => self.p.ident(name),
            CExprKind::Unary { op, operand } => {
                self.p.fixed(op.token());
                self.expr(operand);
            }
            CExprKind::Binary { op, lhs, rhs } => {
                self.expr(lhs);
                self.p.fixed(" ");
                self.p.fixed(op.token());
                self.p.fixed(" ");
                self.expr(rhs);
            }
            CExprKind::Conditional {
                cond,
                then_value,
                else_value,
            } => {
                self.expr(cond);
                self.p.fixed(" ? ");
                self.expr(then_value);
                self.p.fixed(" : ");
                self.expr(else_value);
            }
            CExprKind::Call { callee, args } => {
                match callee {
                    Callee::User(name) => self.p.ident(name),
                    Callee::Fixed(name) => self.p.fixed(name),
                }
                self.p.fixed("(");
                for (index, arg) in args.iter().enumerate() {
                    if index > 0 {
                        self.p.fixed(", ");
                    }
                    self.expr(arg);
                }
                self.p.fixed(")");
            }
            CExprKind::Cast { ty, value } => {
                self.p.fixed("static_cast<");
                self.p.fixed(ty.spelling());
                self.p.fixed(">(");
                self.expr(value);
                self.p.fixed(")");
            }
            CExprKind::Paren(inner) => {
                self.p.fixed("(");
                self.expr(inner);
                self.p.fixed(")");
            }
            CExprKind::Error => self.p.fixed("0 /* error */"),
        }
        for origin in &expr.origins {
            self.p.map(start, origin);
        }
    }
}

/// The operands of a `<<` chain generated for printing (`std::cout`, then
/// each value), or just `expr` if it is not such a chain.
fn stream_operands<'a>(expr: &'a CExpr, out: &mut Vec<&'a CExpr>) {
    match &expr.kind {
        CExprKind::Binary {
            op: BinOp::Shl,
            lhs,
            rhs,
        } if expr.origins.is_empty() => {
            stream_operands(lhs, out);
            out.push(rhs);
        }
        _ => out.push(expr),
    }
}

/// The length in bytes of an expression printed on one line.
fn flat_width(expr: &CExpr) -> usize {
    match &expr.kind {
        CExprKind::Num(lit) => lit.as_str().len(),
        CExprKind::Str(lit) => lit.to_cpp().len(),
        CExprKind::Char(lit) => lit.to_cpp().len(),
        CExprKind::Fixed(text) => text.len(),
        CExprKind::Name(name) => name.as_str().len(),
        CExprKind::Unary { op, operand } => op.token().len() + flat_width(operand),
        CExprKind::Binary { op, lhs, rhs } => flat_width(lhs) + op.token().len() + 2 + flat_width(rhs),
        CExprKind::Conditional {
            cond,
            then_value,
            else_value,
        } => flat_width(cond) + 3 + flat_width(then_value) + 3 + flat_width(else_value),
        CExprKind::Call { callee, args } => {
            let name = match callee {
                Callee::User(name) => name.as_str().len(),
                Callee::Fixed(name) => name.len(),
            };
            name + 2 + args.iter().map(flat_width).sum::<usize>() + 2 * args.len().saturating_sub(1)
        }
        CExprKind::Cast { ty, value } => "static_cast<>()".len() + ty.spelling().len() + flat_width(value),
        CExprKind::Paren(inner) => 2 + flat_width(inner),
        CExprKind::Error => "0 /* error */".len(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shorten_cuts_at_char_boundaries() {
        assert_eq!(shorten("abc"), "abc");
        let long = "é".repeat(MAX_HEADER_NAME_CHARS + 5);
        let short = shorten(&long);
        assert_eq!(short.chars().count(), MAX_HEADER_NAME_CHARS + 1);
        assert!(short.ends_with('…'));
    }
}
