// Generated by Blocks2Cpp 0.1.0 from project "FizzBuzz", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int main() {
    for (int i = 1; i <= 15; ++i) {
        if (i % 15 == 0) {
            std::cout << "FizzBuzz" << '\n';
        } else if (i % 3 == 0) {
            std::cout << "Fizz" << '\n';
        } else if (i % 5 == 0) {
            std::cout << "Buzz" << '\n';
        } else {
            std::cout << i << '\n';
        }
    }
    return 0;
}
