// Generated by Blocks2Cpp 0.1.0 from project "Sum to Ten", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int main() {
    int total = 0;
    for (int i = 1; i <= 10; ++i) {
        total += i;
    }
    std::cout << "Total: " << total << '\n';
    return 0;
}
