//! The five places that list the IPC commands agree, and the security
//! settings are exactly the ones `docs/spec/08-security.md` §8.8 requires.
//!
//! The command list lives in five places that must stay in step
//! (`docs/spec/02-architecture.md` §2.5): the command table
//! (`b2c_ipc::COMMAND_NAMES`, which `build.rs` passes to tauri-build), the
//! `generate_handler!` list in `src/lib.rs`, the capability, the isolation
//! allowlist and the generated permission files.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, missing_docs)]

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

fn manifest_dir() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative: &str) -> String {
    fs::read_to_string(manifest_dir().join(relative)).unwrap()
}

fn json(relative: &str) -> Value {
    serde_json::from_str(&read(relative)).unwrap()
}

fn contract() -> BTreeSet<String> {
    let names: BTreeSet<String> = b2c_ipc::COMMAND_NAMES
        .iter()
        .map(|&name| name.to_owned())
        .collect();
    assert_eq!(names.len(), 36);
    names
}

/// The command names in `tauri::generate_handler![…]` of `src/lib.rs`.
fn handler_list() -> Vec<String> {
    let lib = read("src/lib.rs");
    let start = lib.find("tauri::generate_handler![").unwrap() + "tauri::generate_handler![".len();
    let end = start + lib[start..].find(']').unwrap();
    lib[start..end]
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|path| path.rsplit("::").next().unwrap().to_owned())
        .collect()
}

/// The command names of `isolation/allowlist.generated.js`: its top-level
/// keys, two spaces in.
fn allowlist_keys() -> Vec<String> {
    read("isolation/allowlist.generated.js")
        .lines()
        .filter_map(|line| line.strip_prefix("  "))
        .filter(|line| !line.starts_with(' '))
        .filter_map(|line| line.split_once(": Object.freeze("))
        .map(|(key, _)| key.to_owned())
        .collect()
}

#[test]
fn build_rs_takes_the_command_table() {
    let build = read("build.rs");
    assert!(
        build.contains(".commands(b2c_ipc::COMMAND_NAMES)"),
        "build.rs must give tauri-build the command table"
    );
}

#[test]
fn the_handler_list_is_the_command_table() {
    let handlers = handler_list();
    assert_eq!(handlers.len(), 36, "{handlers:?}");
    let set: BTreeSet<String> = handlers.iter().cloned().collect();
    assert_eq!(set.len(), handlers.len(), "a command is registered twice");
    assert_eq!(set, contract());
    // In table order, so a review sees them in the same place.
    assert_eq!(handlers, b2c_ipc::COMMAND_NAMES);
}

#[test]
fn the_capability_allows_exactly_the_command_table() {
    let capability = json("capabilities/main-window.json");
    let permissions: Vec<&str> = capability["permissions"]
        .as_array()
        .unwrap()
        .iter()
        .map(|permission| permission.as_str().expect("permissions are plain identifiers"))
        .collect();
    let expected: Vec<String> = b2c_ipc::COMMAND_NAMES
        .iter()
        .map(|name| format!("allow-{}", name.replace('_', "-")))
        .collect();
    assert_eq!(permissions, expected);
}

#[test]
fn the_allowlist_names_exactly_the_command_table() {
    let keys = allowlist_keys();
    assert_eq!(keys, b2c_ipc::COMMAND_NAMES);
}

#[test]
fn a_permission_file_exists_for_exactly_the_command_table() {
    let dir = manifest_dir().join("permissions/autogenerated");
    let files: BTreeSet<String> = fs::read_dir(&dir)
        .unwrap()
        .map(|entry| entry.unwrap().file_name().into_string().unwrap())
        .collect();
    let expected: BTreeSet<String> = contract().iter().map(|name| format!("{name}.toml")).collect();
    assert_eq!(files, expected);
    for name in contract() {
        let text = fs::read_to_string(dir.join(format!("{name}.toml"))).unwrap();
        let identifier = format!("identifier = \"allow-{}\"", name.replace('_', "-"));
        assert!(text.contains(&identifier), "{name}.toml: {text}");
        assert!(
            text.contains(&format!("commands.allow = [\"{name}\"]")),
            "{name}.toml"
        );
    }
}

#[test]
fn the_capability_is_for_the_main_window_only_and_grants_nothing_else() {
    let capability = json("capabilities/main-window.json");
    let object = capability.as_object().unwrap();
    let keys: BTreeSet<&str> = object.keys().map(String::as_str).collect();
    assert_eq!(
        keys,
        BTreeSet::from([
            "$schema",
            "identifier",
            "description",
            "local",
            "windows",
            "permissions"
        ]),
        "no remote URLs, webviews or platforms"
    );
    assert_eq!(capability["identifier"], "main-window");
    assert_eq!(capability["local"], true);
    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    for permission in capability["permissions"].as_array().unwrap() {
        let permission = permission.as_str().unwrap();
        assert!(permission.starts_with("allow-"), "{permission}");
        assert!(
            !permission.contains(':'),
            "no core or plugin permission: {permission}"
        );
    }
    // Only this capability exists.
    let files: Vec<PathBuf> = fs::read_dir(manifest_dir().join("capabilities"))
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .collect();
    assert_eq!(files.len(), 1, "{files:?}");
}

/// The Content Security Policy of 08 §8.8, as one line.
fn spec_csp() -> String {
    let spec = fs::read_to_string(manifest_dir().join("../../../docs/spec/08-security.md")).unwrap();
    let section = &spec[spec.find("## 8.8 Webview and IPC hardening").unwrap()..];
    let block = &section[section.find("```text\n").unwrap() + "```text\n".len()..];
    let block = &block[..block.find("```").unwrap()];
    block.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[test]
fn the_security_settings_are_those_of_the_spec() {
    let config = json("tauri.conf.json");
    let security = &config["app"]["security"];
    assert_eq!(security["csp"], spec_csp());
    assert_eq!(
        security["dangerousDisableAssetCspModification"],
        serde_json::json!(["style-src"])
    );
    assert_eq!(security["freezePrototype"], true);
    assert_eq!(
        security["pattern"],
        serde_json::json!({ "use": "isolation", "options": { "dir": "isolation" } })
    );
    assert_eq!(security["capabilities"], serde_json::json!(["main-window"]));
    assert_eq!(config["app"]["withGlobalTauri"], false);
    let windows = config["app"]["windows"].as_array().unwrap();
    assert_eq!(windows.len(), 1);
    assert_eq!(windows[0]["label"], "main");
    assert_eq!(
        windows[0]["create"], false,
        "the window is created in Rust, with its navigation rules"
    );
    assert!(windows[0].get("devtools").is_none());
}

#[test]
fn no_devtools_and_no_permissive_tauri_features() {
    let manifest = read("Cargo.toml");
    for line in manifest
        .lines()
        .map(str::trim)
        .filter(|line| !line.starts_with('#'))
    {
        for forbidden in [
            "\"devtools\"",
            "\"dynamic-acl\"",
            "\"protocol-asset\"",
            "\"shell-open\"",
        ] {
            assert!(
                !line.contains(forbidden),
                "Cargo.toml enables {forbidden}: {line}"
            );
        }
    }
}

#[test]
fn the_isolation_frame_loads_the_allowlist_the_validator_and_the_hook_in_order() {
    let html = read("isolation/index.html");
    let sources: Vec<&str> = html
        .split("<script src=\"")
        .skip(1)
        .map(|rest| &rest[..rest.find('"').unwrap()])
        .collect();
    assert_eq!(sources, ["allowlist.generated.js", "validate.js", "index.js"]);
    assert!(!html.contains("<script>"), "no inline script");
    let hook = read("isolation/index.js");
    assert!(hook.contains("window.__TAURI_ISOLATION_HOOK__"));
    assert!(hook.contains("b2cValidateIpcMessage(message, B2C_IPC_ALLOWLIST)"));
}
