//! The commands through Tauri's IPC, on the mock runtime: every command is
//! registered and answers with typed results or errors, requests are decoded
//! strictly, and build and run sessions stream through real channels in
//! order, ending with exactly one `finished` or `exit` message
//! (`docs/spec/02-architecture.md` §2.5).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, missing_docs)]

mod common;

use std::sync::Arc;

use b2c_ipc::IpcError;
use common::{Harness, NoDialogs, gxx, repo_root, with_printed_text};
use serde_json::{Value, json};
use tauri::ipc::{InvokeBody, InvokeResponseBody};

/// The sample arguments of every command (generated by `b2c-ipc`).
fn samples() -> serde_json::Map<String, Value> {
    let path = repo_root().join("apps/desktop/src-tauri/isolation-tests/samples.generated.json");
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

/// Whether `error` is one of the typed IPC errors (`{ "code": … }`).
fn is_typed(error: &Value) -> bool {
    error["code"]
        .as_str()
        .is_some_and(|code| IpcError::CODES.contains(&code))
}

#[test]
fn every_command_is_registered_and_answers_with_typed_results() {
    let app = Harness::new(Vec::new(), Arc::new(NoDialogs), true);
    let samples = samples();
    assert_eq!(samples.len(), b2c_ipc::COMMAND_NAMES.len());
    for (command, args) in samples {
        // `app_quit` exits the process; the mock runtime cannot.
        if command == "app_quit" {
            continue;
        }
        match app.invoke(&command, args) {
            Ok(response) => assert!(response.is_object(), "{command}: {response}"),
            Err(error) => assert!(is_typed(&error), "{command} gave an untyped error: {error}"),
        }
    }
    let unknown = app.invoke("app_version", json!({})).unwrap_err();
    assert!(!is_typed(&unknown), "{unknown}");
}

#[test]
fn app_info_reports_the_contract_version() {
    let app = Harness::new(Vec::new(), Arc::new(NoDialogs), true);
    let info = app.invoke("app_info", json!({})).unwrap();
    assert_eq!(info["ipcVersion"], b2c_ipc::IPC_VERSION);
    assert_eq!(info["appVersion"], "0.1.0");
    assert_eq!(info["catalogVersion"], b2c_build::CATALOG_VERSION);
}

#[test]
fn bad_requests_get_typed_errors_and_change_nothing() {
    let app = Harness::new(Vec::new(), Arc::new(NoDialogs), true);
    let created = app
        .invoke("project_new", json!({ "request": { "template": "empty" } }))
        .unwrap();
    let handle = created["handle"].as_str().unwrap().to_owned();
    let document = created["document"].as_str().unwrap().to_owned();

    let missing = app.invoke("project_set_dirty", json!({})).unwrap_err();
    assert_eq!(missing["code"], "invalidRequest");
    assert_eq!(missing["reason"], "missingField");

    let unknown_field = app
        .invoke(
            "project_set_dirty",
            json!({ "request": { "handle": handle, "dirty": true, "evil": 1 } }),
        )
        .unwrap_err();
    assert_eq!(unknown_field["code"], "invalidRequest");
    assert_eq!(unknown_field["reason"], "unknownField");
    assert!(!app.backend.has_dirty(), "a refused request changed state");

    let bad_enum = app
        .invoke(
            "project_new",
            json!({ "request": { "template": "guessingGame" } }),
        )
        .unwrap_err();
    assert_eq!(bad_enum["reason"], "badEnum");

    let forged = app
        .invoke(
            "trust_get",
            json!({ "request": { "handle": "ph_ffffffffffffffffffffffffffffffff" } }),
        )
        .unwrap_err();
    assert_eq!(forged["code"], "unknownHandle");

    let malformed_id = app
        .invoke(
            "trust_get",
            json!({ "request": { "handle": "../../etc/passwd" } }),
        )
        .unwrap_err();
    assert_eq!(malformed_id["reason"], "badId");

    let duplicate_key = app
        .invoke(
            "project_save",
            json!({ "request": { "handle": handle, "document": "{\"format\": 1, \"format\": 2}" } }),
        )
        .unwrap_err();
    assert_eq!(duplicate_key["code"], "invalidDocument");

    let input = app
        .invoke(
            "run_input",
            json!({ "request": {
                "runId": "rn_0123456789abcdef0123456789abcdef",
                "data": b2c_ipc::encode_base64(&vec![b'x'; 65_537]),
            } }),
        )
        .unwrap_err();
    assert_eq!(input["code"], "payloadTooLarge", "{input}");

    let resize = app
        .invoke(
            "run_resize",
            json!({ "request": { "runId": "rn_0123456789abcdef0123456789abcdef", "cols": 1, "rows": 24 } }),
        )
        .unwrap_err();
    assert_eq!(resize["reason"], "outOfRange");

    // A raw (bytes) body is not a request at all.
    let raw = app
        .invoke_with("project_new", InvokeBody::Raw(b"{}".to_vec()))
        .unwrap_err();
    assert!(!raw.is_null());

    // The project is still there and still clean.
    assert!(
        app.invoke("trust_get", json!({ "request": { "handle": handle } }))
            .is_ok()
    );
    let saved = app
        .invoke(
            "project_save",
            json!({ "request": { "handle": handle, "document": document } }),
        )
        .unwrap_err();
    assert_eq!(saved["code"], "noPath");
}

#[test]
fn the_app_channel_carries_close_requests() {
    let app = Harness::new(Vec::new(), Arc::new(NoDialogs), true);
    app.invoke("app_subscribe", json!({ "onEvent": "__CHANNEL__:3" }))
        .unwrap();
    let created = app
        .invoke("project_new", json!({ "request": { "template": "empty" } }))
        .unwrap();
    app.invoke(
        "project_set_dirty",
        json!({ "request": { "handle": created["handle"], "dirty": true } }),
    )
    .unwrap();
    assert!(!app.backend.request_close());
    let events = app.events(3);
    assert!(
        events.iter().any(|event| event["kind"] == "closeRequested"),
        "{events:?}"
    );
}

#[test]
fn a_build_streams_progress_then_diagnostics_then_one_finished() {
    let Some(compiler) = gxx() else {
        return;
    };
    let app = Harness::new(
        vec![compiler.parent().unwrap().to_path_buf()],
        Arc::new(NoDialogs),
        true,
    );
    let created = app
        .invoke("project_new", json!({ "request": { "template": "helloWorld" } }))
        .unwrap();
    let started = app
        .invoke(
            "build_start",
            json!({
                "request": { "handle": created["handle"], "document": created["document"], "config": "debug" },
                "onEvent": "__CHANNEL__:7",
            }),
        )
        .unwrap();
    assert!(started["buildId"].as_str().unwrap().starts_with("bd_"));

    let events = app.wait_for(7, "finished");
    let kinds: Vec<&str> = events
        .iter()
        .map(|event| event["kind"].as_str().unwrap())
        .collect();
    assert_eq!(
        kinds.iter().filter(|kind| **kind == "finished").count(),
        1,
        "{kinds:?}"
    );
    assert_eq!(kinds.last(), Some(&"finished"), "{kinds:?}");
    assert!(kinds.contains(&"progress"), "{kinds:?}");
    let last_progress = kinds.iter().rposition(|kind| *kind == "progress").unwrap();
    if let Some(first_diagnostics) = kinds.iter().position(|kind| *kind == "diagnostics") {
        assert!(last_progress < first_diagnostics, "{kinds:?}");
    }
    let finished = events.last().unwrap();
    assert_eq!(finished["outcome"], "built", "{finished}");
    assert_eq!(finished["projectHash"].as_str().map(str::len), Some(64));

    // Nothing arrives after `finished`.
    std::thread::sleep(std::time::Duration::from_millis(200));
    assert_eq!(app.events(7).len(), events.len());
}

#[test]
fn a_run_streams_raw_output_over_8_kib_and_one_exit() {
    let Some(compiler) = gxx() else {
        return;
    };
    let app = Harness::new(
        vec![compiler.parent().unwrap().to_path_buf()],
        Arc::new(NoDialogs),
        true,
    );
    let created = app
        .invoke("project_new", json!({ "request": { "template": "helloWorld" } }))
        .unwrap();
    let text = "x".repeat(30_000);
    let document = with_printed_text(created["document"].as_str().unwrap(), &text);
    let started = app
        .invoke(
            "build_start",
            json!({
                "request": { "handle": created["handle"], "document": document, "config": "debug" },
                "onEvent": "__CHANNEL__:20",
            }),
        )
        .unwrap();
    let built = app.wait_for(20, "finished");
    assert_eq!(built.last().unwrap()["outcome"], "built", "{built:?}");

    let run = app
        .invoke(
            "run_start",
            json!({
                "request": { "buildId": started["buildId"], "runOptions": { "cols": 120, "rows": 30 } },
                "onOutput": "__CHANNEL__:21",
                "onEvent": "__CHANNEL__:22",
            }),
        )
        .unwrap();
    assert!(run["runId"].as_str().unwrap().starts_with("rn_"));

    let events = app.wait_for(22, "exit");
    let kinds: Vec<&str> = events
        .iter()
        .map(|event| event["kind"].as_str().unwrap())
        .collect();
    assert_eq!(kinds.first(), Some(&"started"), "{kinds:?}");
    assert_eq!(kinds.last(), Some(&"exit"), "{kinds:?}");
    assert_eq!(
        kinds.iter().filter(|kind| **kind == "exit").count(),
        1,
        "{kinds:?}"
    );
    let exit = events.last().unwrap();
    assert_eq!(exit["status"], json!({ "type": "exited", "code": 0 }), "{exit}");

    let batches: Vec<Vec<u8>> = app
        .messages(21)
        .into_iter()
        .map(|body| match body {
            InvokeResponseBody::Raw(bytes) => bytes,
            InvokeResponseBody::Json(json) => panic!("output must be raw bytes, got {json}"),
        })
        .collect();
    assert_eq!(
        exit["afterSeq"],
        batches.len(),
        "every batch is sent before the exit"
    );
    let output = batches.concat();
    let shown = String::from_utf8_lossy(&output).matches('x').count();
    assert_eq!(shown, text.len());
    let largest = batches.iter().map(Vec::len).max().unwrap_or(0);
    assert!(largest > 8 * 1024, "the largest batch has only {largest} bytes");
}
