// Generated by Blocks2Cpp 0.1.0 from project "Times Table", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int main() {
    for (int row = 1; row <= 5; ++row) {
        for (int col = 1; col <= 5; ++col) {
            if (col < 5) {
                std::cout << row * col << " ";
            } else {
                std::cout << row * col << '\n';
            }
        }
    }
    return 0;
}
