// Generated by Blocks2Cpp 0.1.0 from project "Exit Code", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <cstdlib>
#include <iostream>

void stopEarly();

void stopEarly() {
    std::cout << "Stopping early" << '\n';
    std::exit(3);
}

int main() {
    std::cout << "Checking..." << '\n';
    stopEarly();
    std::cout << "This line is never printed" << '\n';
    return 0;
}
