// Generated by Blocks2Cpp 0.1.0 from project "Weather Advice", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int main() {
    bool raining = true;
    bool umbrella = false;
    double temperature = 12.5;
    std::cout << "Get wet: " << (raining && !umbrella ? "true" : "false") << '\n';
    std::cout << (raining ? "Stay inside" : "Go out") << '\n';
    std::cout << "Cold: " << (temperature < 5 ? "true" : "false") << '\n';
    return 0;
}
