// Generated by Blocks2Cpp 0.1.0 from project "Prime Numbers", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

bool isPrime(int n);

bool isPrime(int n) {
    if (n < 2) {
        return false;
    }
    int divisor = 2;
    while (divisor * divisor <= n) {
        if (n % divisor == 0) {
            return false;
        }
        ++divisor;
    }
    return true;
}

int main() {
    int count = 0;
    for (int k = 1; k <= 50; ++k) {
        if (isPrime(k)) {
            if (count > 0) {
                std::cout << " ";
            }
            std::cout << k;
            ++count;
        }
    }
    std::cout << "" << '\n';
    std::cout << "Found " << count << " primes" << '\n';
    return 0;
}
