#!/usr/bin/env python3
"""Generates crates/b2c-ir/src/reserved_names.rs from the local g++.

Two lists are produced (docs/spec/08-security.md §8.4.1):

* MACRO_NAMES: object-like or function-like macros that the standard library
  headers (and g++'s predefines, in both strict and GNU modes) define without a
  leading underscore. A user identifier with one of these names would be
  rewritten by the preprocessor, so they are rejected at every scope.
* GLOBAL_NAMES: names that the standard headers declare in the global namespace
  (C library functions such as `abs`, `y1` or `index`). A user function, global
  variable or type with one of these names clashes with the library, so they are
  rejected at namespace scope.

Usage: python3 tools/gen-reserved-names.py [g++]   (run from the repository root)
The output is deterministic for a given compiler; review the diff when regenerating.
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

GXX = sys.argv[1] if len(sys.argv) > 1 else "g++"
OUT = Path("crates/b2c-ir/src/reserved_names.rs")
IDENT = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")

# Extra names from other platforms' headers (MinGW-w64 math.h in GNU mode, POSIX).
EXTRA_MACROS = {"DOMAIN", "SING", "OVERFLOW", "UNDERFLOW", "TLOSS", "PLOSS", "NDEBUG"}


def run(args, stdin):
    return subprocess.run(args, input=stdin, capture_output=True, text=True, check=False)


def macros(std):
    src = "#include <bits/stdc++.h>\n#include <cassert>\n"
    out = run([GXX, f"-std={std}", "-x", "c++", "-dM", "-E", "-"], src).stdout
    names = set()
    for line in out.splitlines():
        m = re.match(r"#define\s+([A-Za-z_][A-Za-z0-9_]*)", line)
        if m and IDENT.match(m.group(1)):
            names.add(m.group(1))
    return names


def global_names(all_macros):
    pre = run([GXX, "-std=gnu++20", "-x", "c++", "-E", "-P", "-"], "#include <bits/stdc++.h>\n").stdout
    candidates = sorted({w for w in re.findall(r"\b[A-Za-z][A-Za-z0-9_]*\b", pre)} - all_macros)
    # `using ::NAME;` compiles only if NAME is declared in the global namespace.
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "probe.cpp"
        lines = ["#include <bits/stdc++.h>"]
        lines += [f"namespace b2c_probe_{i} {{ using ::{n}; }}" for i, n in enumerate(candidates)]
        src.write_text("\n".join(lines) + "\n")
        res = run([GXX, "-std=gnu++20", "-fsyntax-only", "-fmax-errors=0", str(src)], "")
    failed_lines = {int(m.group(1)) for m in re.finditer(r"probe\.cpp:(\d+):\d+: error", res.stderr)}
    declared = set()
    for i, name in enumerate(candidates):
        if (i + 2) not in failed_lines:  # line 1 is the #include
            declared.add(name)
    return declared


def rust_array(name, doc, items):
    body = "\n".join(f'    "{n}",' for n in sorted(items))
    return f"{doc}\npub(crate) const {name}: &[&str] = &[\n{body}\n];\n"


def main():
    version = run([GXX, "-dumpfullversion"], "").stdout.strip()
    target = run([GXX, "-dumpmachine"], "").stdout.strip()
    all_macros = macros("c++20") | macros("gnu++20") | EXTRA_MACROS
    globals_ = global_names(all_macros)
    header = (
        "// @generated by tools/gen-reserved-names.py — do not edit by hand.\n"
        f"// Source compiler: g++ {version} ({target}). Sorted for binary search.\n\n"
    )
    text = header
    text += rust_array(
        "MACRO_NAMES",
        "/// Macros defined by the standard headers or g++ predefines (any scope).",
        all_macros,
    )
    text += "\n" + rust_array(
        "GLOBAL_NAMES",
        "/// Names the standard headers declare in the global namespace (namespace scope).",
        globals_,
    )
    OUT.write_text(text)
    print(f"{OUT}: {len(all_macros)} macros, {len(globals_)} global names")


if __name__ == "__main__":
    main()
