[package]
name = "b2c-cli"
description = "The b2c command-line tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "b2c"
path = "src/main.rs"

[dependencies]
b2c-build.workspace = true
b2c-ir.workspace = true
b2c-model.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
