// Generated by Blocks2Cpp 0.1.0 from project "Tricky Text", module "main".
// Edit the blocks, not this file – changes here are overwritten.

#include <iostream>

int main() {
    // This comment ends with a backslash \ //
    std::cout << "Quote: \" Backslash: \\ Tab:\tend" << '\n';
    std::cout << "Question marks: ?\?/ ?\?= ok" << '\n';
    std::cout << "Unicode: héllo ✓ — 日本" << '\n';
    std::cout << "Letter: " << 'A' << '\n';
    return 0;
}
